CREATE_DOGS_TABLE = """
CREATE TABLE IF NOT EXISTS Dogs (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    BreedID INTEGER NOT NULL,
    Age INTEGER NOT NULL,
    Sex INTEGER NOT NULL,
    Description TEXT NULL,
    OwnerID INTEGER NOT NULL,
    CONSTRAINT fk_DogsBreedID
        FOREIGN KEY(BreedID) 
        REFERENCES Breeds(ID) 
        ON DELETE CASCADE,
    CONSTRAINT fk_DogsUserID
        FOREIGN KEY(OwnerID) 
        REFERENCES Users(ID) 
        ON DELETE CASCADE
);
"""

CREATE_BREEDS_TABLE = """
CREATE TABLE IF NOT EXISTS Breeds (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL
);
"""

CREATE_USERS_TABLE = """
CREATE TABLE IF NOT EXISTS Users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL,
    Password TEXT NOT NULL,
    Name TEXT NULL,
    Surname TEXT NULL,
    Email TEXT NOT NULL
);
"""

CREATE_LOCATIONS_TABLE = """
CREATE TABLE IF NOT EXISTS Locations (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Latitude REAL NOT NULL,
    Longitude REAL NOT NULL,
    UserID INTEGER NOT NULL,
    DogID INTEGER NOT NULL,
    CONSTRAINT fk_LocationsUserID
        FOREIGN KEY(UserID)
        REFERENCES Users(ID)
        ON DELETE CASCADE,
    CONSTRAINT fk_LocationsDogID
        FOREIGN KEY(DogID)
        REFERENCES Dogs(ID)
);
"""

CREATE_PICTURES_TABLE = """
CREATE TABLE IF NOT EXISTS Pictures (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Url TEXT NOT NULL,
    DogID INTEGER NOT NULL,
    CONSTRAINT fk_PicturesDogID
        FOREIGN KEY(DogID)
        REFERENCES Dogs(ID)
        ON DELETE CASCADE
);
"""